package grammartools.ui.options;

import grammartools.GrammarTools.ClassifyOptions;
import grammartools.ui.SwingUtils;
import grammartools.util.SentenceInstance;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.ListModel;
import org.fife.ui.rsyntaxtextarea.SyntaxConstants;

@SuppressWarnings("serial")
public class ClassifyConfigPanel extends javax.swing.JPanel implements ConfigPanel
{
    public ClassifyConfigPanel()
    {
        initComponents();
               
        try
        {
            functionSyntaxTextArea.setText(grammartools.GrammarTools.getDefaultFunctionScript());
        }
        catch(NoSuchFieldException e)
        {
            functionSyntaxTextArea.setText("/*\nInitialization Error:\n" + e.getLocalizedMessage() + "*/");
        }
        
        editFunctionDialog.pack();
        functionSyntaxTextArea.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_JAVASCRIPT);
        functionSyntaxTextArea.setCodeFoldingEnabled(true);
        functionSyntaxTextArea.setAntiAliasingEnabled(true);
    }
    
    @Override
    public ClassifyOptions getConfig()
    {
        ClassifyOptions o = new ClassifyOptions();
        o.functionScript = functionSyntaxTextArea.getText();
        o.grammarFile = inputGrammarFileTextField.getText();
        o.modelFile = inputClassifierModelTextField.getText();
        o.isNumericClass = numericGrammaticalRadioButton.isSelected();
        o.errorThreshold = (Double)nGrammaticalErrorsThreshold.getValue();
        o.showCorrect = correctCheckBox.isSelected();
        o.showIncorrect = IncorrectCheckBox.isSelected();
        return o;
    }
    
    @Override
    public String getConfigErrors()
    {
        String errors = "";
        
        ClassifyOptions o = getConfig();
        if(!new File(o.modelFile).isFile()) errors += "classifier model file does not exist\n";
        if(!o.grammarFile.isEmpty() && !new File(o.grammarFile).isFile()) errors += "prolog grammar file does not exist\n";
        if(o.isNumericClass && o.errorThreshold < 0) errors += "errors threshold must be 0 or greater\n";
        
        return errors.isEmpty() ? null : errors;
    }
        
    private ListModel getVariablesListModel()
    {
        DefaultListModel model = new DefaultListModel();
        for(String v : SentenceInstance.getAttributeNames())
            model.addElement(v);       
        return model;
    }
    
    private void updateGrammaticalClassTypeLayout()
    {
        grammaticalClassTypePanel.removeAll();
        if(numericGrammaticalRadioButton.isSelected())
            grammaticalClassTypePanel.add(numericPanel);
        grammaticalClassTypePanel.revalidate();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        grammaticalClassTypeButtonGroup = new javax.swing.ButtonGroup();
        numericPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        nGrammaticalErrorsThreshold = new javax.swing.JSpinner();
        editFunctionDialog = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        codeSplitPane = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        functionSyntaxTextArea = new org.fife.ui.rsyntaxtextarea.RSyntaxTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        variablesList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        openButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        editFunctionButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        browseForGrammarInput = new javax.swing.JButton();
        inputGrammarFileTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        binaryGrammaticalRadioButton = new javax.swing.JRadioButton();
        numericGrammaticalRadioButton = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        browseForClassifierModelInput = new javax.swing.JButton();
        inputClassifierModelTextField = new javax.swing.JTextField();
        grammaticalClassTypePanel = new javax.swing.JPanel();
        correctCheckBox = new javax.swing.JCheckBox();
        IncorrectCheckBox = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();

        jLabel3.setLabelFor(nGrammaticalErrorsThreshold);
        jLabel3.setText("Threshold:");

        nGrammaticalErrorsThreshold.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(1.0d)));
        nGrammaticalErrorsThreshold.setToolTipText("Sentence containing no more than this many errors are considered correct");

        javax.swing.GroupLayout numericPanelLayout = new javax.swing.GroupLayout(numericPanel);
        numericPanel.setLayout(numericPanelLayout);
        numericPanelLayout.setHorizontalGroup(
            numericPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(numericPanelLayout.createSequentialGroup()
                .addGroup(numericPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(nGrammaticalErrorsThreshold, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        numericPanelLayout.setVerticalGroup(
            numericPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(numericPanelLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(2, 2, 2)
                .addComponent(nGrammaticalErrorsThreshold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        editFunctionDialog.setTitle("Edit Function");
        editFunctionDialog.setName("editFunctionDialog"); // NOI18N

        jLabel2.setDisplayedMnemonic('f');
        jLabel2.setText("Enter javascript code:");

        codeSplitPane.setDividerSize(6);
        codeSplitPane.setResizeWeight(0.9);
        codeSplitPane.setOneTouchExpandable(true);

        functionSyntaxTextArea.setColumns(20);
        functionSyntaxTextArea.setRows(5);
        jScrollPane1.setViewportView(functionSyntaxTextArea);

        codeSplitPane.setLeftComponent(jScrollPane1);

        variablesList.setModel(getVariablesListModel());
        variablesList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        variablesList.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                variablesListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(variablesList);

        codeSplitPane.setRightComponent(jScrollPane2);

        jLabel1.setText("Variables:");

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        openButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16/document-open.png"))); // NOI18N
        openButton.setMnemonic('o');
        openButton.setToolTipText("Open script file");
        openButton.setFocusable(false);
        openButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        openButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        openButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                openButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(openButton);

        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16/document-save.png"))); // NOI18N
        saveButton.setMnemonic('s');
        saveButton.setToolTipText("Save script file");
        saveButton.setFocusable(false);
        saveButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saveButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        saveButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                saveButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(saveButton);

        javax.swing.GroupLayout editFunctionDialogLayout = new javax.swing.GroupLayout(editFunctionDialog.getContentPane());
        editFunctionDialog.getContentPane().setLayout(editFunctionDialogLayout);
        editFunctionDialogLayout.setHorizontalGroup(
            editFunctionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(codeSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
            .addGroup(editFunctionDialogLayout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        editFunctionDialogLayout.setVerticalGroup(
            editFunctionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editFunctionDialogLayout.createSequentialGroup()
                .addGroup(editFunctionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(editFunctionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1))
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(codeSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
        );

        editFunctionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit-function.png"))); // NOI18N
        editFunctionButton.setMnemonic('e');
        editFunctionButton.setText("Edit function");
        editFunctionButton.setToolTipText("Create/modify a function over sentence features");
        editFunctionButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                editFunctionButtonActionPerformed(evt);
            }
        });

        jLabel7.setDisplayedMnemonic('o');
        jLabel7.setLabelFor(inputGrammarFileTextField);
        jLabel7.setText("Prolog grammar file:");

        browseForGrammarInput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16/document-open.png"))); // NOI18N
        browseForGrammarInput.setToolTipText("Browse");
        browseForGrammarInput.setMargin(new java.awt.Insets(0, 0, 0, 0));
        browseForGrammarInput.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                browseForGrammarInputActionPerformed(evt);
            }
        });

        inputGrammarFileTextField.setFont(inputGrammarFileTextField.getFont());
        inputGrammarFileTextField.setText(DEF_INPUT_GRAMMAR_FILE);
        inputGrammarFileTextField.setToolTipText("The location of the prolog file containing DCG rules");

        jLabel6.setLabelFor(binaryGrammaticalRadioButton);
        jLabel6.setText("Grammatical class type:");

        grammaticalClassTypeButtonGroup.add(binaryGrammaticalRadioButton);
        binaryGrammaticalRadioButton.setMnemonic('b');
        binaryGrammaticalRadioButton.setSelected(true);
        binaryGrammaticalRadioButton.setText("Binary");
        binaryGrammaticalRadioButton.setToolTipText("Use binary nominal classes: grammatically correct or incorrect");
        binaryGrammaticalRadioButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                binaryGrammaticalRadioButtonActionPerformed(evt);
            }
        });

        grammaticalClassTypeButtonGroup.add(numericGrammaticalRadioButton);
        numericGrammaticalRadioButton.setMnemonic('n');
        numericGrammaticalRadioButton.setText("Numeric ");
        numericGrammaticalRadioButton.setToolTipText("Use numeric class: number of grammatical errors present");
        numericGrammaticalRadioButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                numericGrammaticalRadioButtonActionPerformed(evt);
            }
        });

        jLabel8.setDisplayedMnemonic('o');
        jLabel8.setLabelFor(inputClassifierModelTextField);
        jLabel8.setText("Weka classifier model file:");

        browseForClassifierModelInput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16/document-open.png"))); // NOI18N
        browseForClassifierModelInput.setToolTipText("Browse");
        browseForClassifierModelInput.setMargin(new java.awt.Insets(0, 0, 0, 0));
        browseForClassifierModelInput.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                browseForClassifierModelInputActionPerformed(evt);
            }
        });

        inputClassifierModelTextField.setFont(inputClassifierModelTextField.getFont());
        inputClassifierModelTextField.setText(DEF_INPUT_CLASSIFIER_FILE);
        inputClassifierModelTextField.setToolTipText("The location of the classifier model file generated by Weka");

        grammaticalClassTypePanel.setLayout(new javax.swing.BoxLayout(grammaticalClassTypePanel, javax.swing.BoxLayout.LINE_AXIS));

        correctCheckBox.setSelected(true);
        correctCheckBox.setText("Correct");
        correctCheckBox.setToolTipText("Display sentences that are grammatically correct");

        IncorrectCheckBox.setSelected(true);
        IncorrectCheckBox.setText("Incorrect");
        IncorrectCheckBox.setToolTipText("Display sentences that are grammatically incorrect");

        jLabel4.setText("Show grammatically...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editFunctionButton)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numericGrammaticalRadioButton)
                                    .addComponent(binaryGrammaticalRadioButton)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(grammaticalClassTypePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(browseForGrammarInput)
                                .addGap(0, 0, 0)
                                .addComponent(inputGrammarFileTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(correctCheckBox)
                                    .addComponent(jLabel7)
                                    .addComponent(IncorrectCheckBox)
                                    .addComponent(jLabel4))
                                .addGap(0, 51, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(browseForClassifierModelInput)
                        .addGap(0, 0, 0)
                        .addComponent(inputClassifierModelTextField)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editFunctionButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(browseForGrammarInput, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inputGrammarFileTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(correctCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IncorrectCheckBox))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(binaryGrammaticalRadioButton)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(numericGrammaticalRadioButton))))
                            .addComponent(grammaticalClassTypePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(browseForClassifierModelInput, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inputClassifierModelTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editFunctionButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_editFunctionButtonActionPerformed
    {//GEN-HEADEREND:event_editFunctionButtonActionPerformed
        editFunctionDialog.setVisible(true);
    }//GEN-LAST:event_editFunctionButtonActionPerformed

    private void variablesListMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_variablesListMouseClicked
    {//GEN-HEADEREND:event_variablesListMouseClicked
        if(evt.getClickCount() == 2 && variablesList.getSelectedValue() != null)
        {
            functionSyntaxTextArea.insert(
                variablesList.getSelectedValue().toString(),
                functionSyntaxTextArea.getCaretPosition());
        }
    }//GEN-LAST:event_variablesListMouseClicked

    private void openButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_openButtonActionPerformed
    {//GEN-HEADEREND:event_openButtonActionPerformed
        javax.swing.filechooser.FileNameExtensionFilter filter = 
            new javax.swing.filechooser.FileNameExtensionFilter("JavaScript Files [.js]", "js");
        
        String file = SwingUtils.browseForFile(
            editFunctionDialog, (inputFile == null ? DEF_INPUT_FILE : inputFile), JFileChooser.FILES_ONLY,
            "Open a script file",
            filter);

        if(file != null)
        {
            try
            {
                final BufferedReader in = new BufferedReader(new FileReader(file));
                final StringBuilder sb = new StringBuilder();
                String line;
                while((line = in.readLine()) != null)                  
                    sb.append(line + "\n");
                in.close();
                functionSyntaxTextArea.setText(sb.toString());
                inputFile = file;
            }
            catch(IOException e) 
            {
                SwingUtils.showWarning(editFunctionDialog, "Could not open file." , "Warning");
            }
        }
    }//GEN-LAST:event_openButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_saveButtonActionPerformed
    {//GEN-HEADEREND:event_saveButtonActionPerformed
        javax.swing.filechooser.FileNameExtensionFilter filter = 
            new javax.swing.filechooser.FileNameExtensionFilter("JavaScript Files [.js]", "js");
        
        String file = SwingUtils.browseForFile(
            editFunctionDialog, (inputFile == null ? DEF_INPUT_FILE : inputFile), JFileChooser.FILES_ONLY,
            "Save to script file",
            filter);

        if(file != null)
        {
            String s = functionSyntaxTextArea.getText();
            try
            {
                BufferedWriter out = new BufferedWriter(new FileWriter(file, false));
                out.write(s);
                out.close();
                inputFile = file;
            }
            catch(IOException e) 
            {
                SwingUtils.showWarning(editFunctionDialog, "Could not write file." , "Warning");
            }
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void browseForGrammarInputActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_browseForGrammarInputActionPerformed
    {//GEN-HEADEREND:event_browseForGrammarInputActionPerformed
        javax.swing.filechooser.FileNameExtensionFilter filter =
        new javax.swing.filechooser.FileNameExtensionFilter("Prolog Files [.pl]", "pl");

        String input = inputGrammarFileTextField.getText();
        String file = SwingUtils.browseForFile(
            (java.awt.Window)this.getTopLevelAncestor(),
            (input.isEmpty() ? DEF_INPUT_GRAMMAR_FILE : input), JFileChooser.FILES_ONLY,
            "Select an input file",
            filter);

        if(file != null)
        {
            if(new File(file).isFile())
            {
                inputGrammarFileTextField.setText(file);
            }
            else
            {
                SwingUtils.showWarning((java.awt.Window)this.getTopLevelAncestor(),
                    "File does not exist." , "Warning");
            }
        }
    }//GEN-LAST:event_browseForGrammarInputActionPerformed

    private void browseForClassifierModelInputActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_browseForClassifierModelInputActionPerformed
    {//GEN-HEADEREND:event_browseForClassifierModelInputActionPerformed
        javax.swing.filechooser.FileNameExtensionFilter filter =
            new javax.swing.filechooser.FileNameExtensionFilter("Classifier Model Files [.model]", "model");

        String input = inputClassifierModelTextField.getText();
        String file = SwingUtils.browseForFile(
            (java.awt.Window)this.getTopLevelAncestor(),
            (input.isEmpty() ? DEF_INPUT_CLASSIFIER_FILE : input), JFileChooser.FILES_ONLY,
            "Select a classifier model file",
            filter);

        if(file != null)
        {
            if(new File(file).isFile())
            {
                inputClassifierModelTextField.setText(file);
            }
            else
            {
                SwingUtils.showWarning((java.awt.Window)this.getTopLevelAncestor(),
                    "File does not exist." , "Warning");
            }
        }
    }//GEN-LAST:event_browseForClassifierModelInputActionPerformed

    private void binaryGrammaticalRadioButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_binaryGrammaticalRadioButtonActionPerformed
    {//GEN-HEADEREND:event_binaryGrammaticalRadioButtonActionPerformed
        updateGrammaticalClassTypeLayout();
    }//GEN-LAST:event_binaryGrammaticalRadioButtonActionPerformed

    private void numericGrammaticalRadioButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_numericGrammaticalRadioButtonActionPerformed
    {//GEN-HEADEREND:event_numericGrammaticalRadioButtonActionPerformed
        updateGrammaticalClassTypeLayout();
    }//GEN-LAST:event_numericGrammaticalRadioButtonActionPerformed
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox IncorrectCheckBox;
    private javax.swing.JRadioButton binaryGrammaticalRadioButton;
    private javax.swing.JButton browseForClassifierModelInput;
    private javax.swing.JButton browseForGrammarInput;
    private javax.swing.JSplitPane codeSplitPane;
    private javax.swing.JCheckBox correctCheckBox;
    private javax.swing.JButton editFunctionButton;
    private javax.swing.JDialog editFunctionDialog;
    private org.fife.ui.rsyntaxtextarea.RSyntaxTextArea functionSyntaxTextArea;
    private javax.swing.ButtonGroup grammaticalClassTypeButtonGroup;
    private javax.swing.JPanel grammaticalClassTypePanel;
    private javax.swing.JTextField inputClassifierModelTextField;
    private javax.swing.JTextField inputGrammarFileTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JSpinner nGrammaticalErrorsThreshold;
    private javax.swing.JRadioButton numericGrammaticalRadioButton;
    private javax.swing.JPanel numericPanel;
    private javax.swing.JButton openButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JList variablesList;
    // End of variables declaration//GEN-END:variables

    private String inputFile = null;
    private static final String DEF_INPUT_FILE = "function.js";
    private static final String DEF_INPUT_GRAMMAR_FILE = "grammar.pl";
    private static final String DEF_INPUT_CLASSIFIER_FILE = "classifier.model";
}
