package grammartools.ui.options;

import grammartools.GrammarTools.TagOptions;

@SuppressWarnings("serial")
public class TagConfigPanel extends javax.swing.JPanel implements ConfigPanel
{
    public TagConfigPanel()
    {
        initComponents();
    }
    
    @Override
    public TagOptions getConfig()
    {
        TagOptions o = new TagOptions();
        o.maxResults = (Integer)maxResultsSpinner.getValue();
        o.showProbs = true;
        return o;
    }
    
    @Override
    public String getConfigErrors()
    {
        String errors = "";

        TagOptions o = getConfig();
        if(o.maxResults < 1) errors += "max results must be > than 0";

        return errors.isEmpty() ? null : errors;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        maxResultsSpinner = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();

        maxResultsSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        maxResultsSpinner.setPreferredSize(new java.awt.Dimension(40, 18));

        jLabel1.setLabelFor(maxResultsSpinner);
        jLabel1.setText("Max results:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maxResultsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxResultsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSpinner maxResultsSpinner;
    // End of variables declaration//GEN-END:variables
}
