package grammartools.ui;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.File;
import java.util.LinkedList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

@SuppressWarnings("serial")
public class GrammarToolsFrame extends javax.swing.JFrame
{
    public GrammarToolsFrame()
    {        
        initComponents();        
        updateLaunchButton();
    }
    
    private ListModel getToolListModel()
    {
        DefaultListModel m = new DefaultListModel();
        for(ToolType t : ToolType.values())
        {
            m.addElement(t);
        }
        return m;
    }
    
    private boolean isLaunchValid()
    {
        return !toolList.isSelectionEmpty();
    }
    
    private void updateLaunchButton()
    {
        launchButton.setEnabled(isLaunchValid());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        optionsDialog = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        opennlpModelsTextField = new javax.swing.JTextField();
        browseForOpenNLPModelsButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        stanfordModelsTextField = new javax.swing.JTextField();
        browseForStanfordNLPModels = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        toolList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        toolTextPane = new javax.swing.JTextPane();
        buttonsToolbar = new javax.swing.JToolBar();
        launchButton = new javax.swing.JButton();
        optionsButton = new javax.swing.JButton();

        optionsDialog.setTitle("Options");
        optionsDialog.setLocationByPlatform(true);
        optionsDialog.addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                optionsDialogWindowOpened(evt);
            }
        });

        jLabel4.setText("OpenNLP models path:");

        opennlpModelsTextField.setEditable(false);
        opennlpModelsTextField.setFont(opennlpModelsTextField.getFont());
        opennlpModelsTextField.setText(DEF_OPENNLP_MODEL_PATH);

        browseForOpenNLPModelsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16/document-open.png"))); // NOI18N
        browseForOpenNLPModelsButton.setToolTipText("Browse");
        browseForOpenNLPModelsButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        browseForOpenNLPModelsButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                browseForOpenNLPModelsButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Stanford models path:");

        stanfordModelsTextField.setEditable(false);
        stanfordModelsTextField.setFont(stanfordModelsTextField.getFont());
        stanfordModelsTextField.setText(DEF_STANFORD_MODEL_PATH);

        browseForStanfordNLPModels.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16/document-open.png"))); // NOI18N
        browseForStanfordNLPModels.setToolTipText("Browse");
        browseForStanfordNLPModels.setMargin(new java.awt.Insets(0, 0, 0, 0));
        browseForStanfordNLPModels.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                browseForStanfordNLPModelsActionPerformed(evt);
            }
        });

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout optionsDialogLayout = new javax.swing.GroupLayout(optionsDialog.getContentPane());
        optionsDialog.getContentPane().setLayout(optionsDialogLayout);
        optionsDialogLayout.setHorizontalGroup(
            optionsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(optionsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(optionsDialogLayout.createSequentialGroup()
                        .addComponent(browseForOpenNLPModelsButton)
                        .addGap(0, 0, 0)
                        .addComponent(opennlpModelsTextField)
                        .addContainerGap())
                    .addGroup(optionsDialogLayout.createSequentialGroup()
                        .addGroup(optionsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(optionsDialogLayout.createSequentialGroup()
                                .addComponent(browseForStanfordNLPModels)
                                .addGap(0, 0, 0)
                                .addComponent(stanfordModelsTextField))
                            .addGroup(optionsDialogLayout.createSequentialGroup()
                                .addGroup(optionsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(closeButton)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(0, 226, Short.MAX_VALUE)))
                        .addGap(10, 10, 10))))
        );
        optionsDialogLayout.setVerticalGroup(
            optionsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsDialogLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(optionsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(browseForOpenNLPModelsButton)
                    .addComponent(opennlpModelsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(optionsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(browseForStanfordNLPModels)
                    .addComponent(stanfordModelsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(closeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("GrammarTools");
        setLocationByPlatform(true);
        setName("GrammarTools"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });

        toolList.setFont(toolList.getFont().deriveFont(toolList.getFont().getSize()+1f));
        toolList.setModel(getToolListModel());
        toolList.addListSelectionListener(new javax.swing.event.ListSelectionListener()
        {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt)
            {
                toolListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(toolList);

        jLabel1.setText("Choose a Tool:");

        toolTextPane.setEditable(false);
        jScrollPane2.setViewportView(toolTextPane);

        buttonsToolbar.setFloatable(false);
        buttonsToolbar.setRollover(true);
        buttonsToolbar.setFont(buttonsToolbar.getFont());

        launchButton.setFont(launchButton.getFont());
        launchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/media-playback-start.png"))); // NOI18N
        launchButton.setMnemonic('l');
        launchButton.setText("Launch");
        launchButton.setToolTipText("Launch the selected tool");
        launchButton.setEnabled(isLaunchValid());
        launchButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        launchButton.setMargin(new java.awt.Insets(4, 4, 4, 4));
        launchButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        launchButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                launchButtonActionPerformed(evt);
            }
        });
        buttonsToolbar.add(launchButton);

        optionsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/applications-system.png"))); // NOI18N
        optionsButton.setMnemonic('o');
        optionsButton.setText("Options");
        optionsButton.setToolTipText("Configure options");
        optionsButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        optionsButton.setMargin(new java.awt.Insets(4, 4, 4, 4));
        optionsButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        optionsButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                optionsButtonActionPerformed(evt);
            }
        });
        buttonsToolbar.add(optionsButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(buttonsToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonsToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))
                .addGap(4, 4, 4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void launchButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_launchButtonActionPerformed
    {//GEN-HEADEREND:event_launchButtonActionPerformed
        final String opennlpModelsPath = opennlpModelsTextField.getText();
        final String stanfordModelsPath = stanfordModelsTextField.getText();
        for(Object t : toolList.getSelectedValues())
        {
            final JFrame f = new ToolFrame((ToolType)t, opennlpModelsPath, stanfordModelsPath);
            f.setVisible(true);
            f.addWindowListener(new WindowAdapter()
            {
                @Override
                public void windowClosed(WindowEvent e)
                {
                    currentlyOpenWindows.remove(f);
                }
            });
            currentlyOpenWindows.add(f);
        }
    }//GEN-LAST:event_launchButtonActionPerformed

    private void optionsButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_optionsButtonActionPerformed
    {//GEN-HEADEREND:event_optionsButtonActionPerformed
        optionsDialog.setVisible(true);
    }//GEN-LAST:event_optionsButtonActionPerformed

    private void toolListValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_toolListValueChanged
    {//GEN-HEADEREND:event_toolListValueChanged
        updateLaunchButton();
        
        String desc = "";
        for(Object t : toolList.getSelectedValues())
        {
            desc += ((ToolType)t).getDescription() + "\n\n";
        }
        toolTextPane.setText(desc);
    }//GEN-LAST:event_toolListValueChanged

    private void browseForOpenNLPModelsButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_browseForOpenNLPModelsButtonActionPerformed
    {//GEN-HEADEREND:event_browseForOpenNLPModelsButtonActionPerformed

        String file = SwingUtils.browseForFile(optionsDialog, opennlpModelsTextField.getText(), JFileChooser.DIRECTORIES_ONLY, "Select directory of OpenNLP models");
        if(file != null && !new File(file).equals(new File(opennlpModelsTextField.getText())))
        {
            opennlpModelsTextField.setText(file);
            opennlpModelsTextField.updateUI();
        }
    }//GEN-LAST:event_browseForOpenNLPModelsButtonActionPerformed

    private void browseForStanfordNLPModelsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_browseForStanfordNLPModelsActionPerformed
    {//GEN-HEADEREND:event_browseForStanfordNLPModelsActionPerformed

        String file = SwingUtils.browseForFile(optionsDialog, stanfordModelsTextField.getText(), JFileChooser.DIRECTORIES_ONLY, "Select directory of Stanford models");
        if(file != null && !new File(file).equals(new File(stanfordModelsTextField.getText())))
        {
            stanfordModelsTextField.setText(file);
            stanfordModelsTextField.updateUI();
        }
    }//GEN-LAST:event_browseForStanfordNLPModelsActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_closeButtonActionPerformed
    {//GEN-HEADEREND:event_closeButtonActionPerformed
        optionsDialog.setVisible(false);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void optionsDialogWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_optionsDialogWindowOpened
    {//GEN-HEADEREND:event_optionsDialogWindowOpened
        optionsDialog.pack();
    }//GEN-LAST:event_optionsDialogWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        if(!currentlyOpenWindows.isEmpty()
        && JOptionPane.showConfirmDialog(this,
                    "There are still active tool windows open, do you wish to exit anyways?",
                    "Confirm Exit", JOptionPane.YES_NO_OPTION)
                    != JOptionPane.YES_OPTION)
        {
            return;
        }
        
        this.dispose();
        System.exit(0);        
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseForOpenNLPModelsButton;
    private javax.swing.JButton browseForStanfordNLPModels;
    private javax.swing.JToolBar buttonsToolbar;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton launchButton;
    private javax.swing.JTextField opennlpModelsTextField;
    private javax.swing.JButton optionsButton;
    private javax.swing.JDialog optionsDialog;
    private javax.swing.JTextField stanfordModelsTextField;
    private javax.swing.JList toolList;
    private javax.swing.JTextPane toolTextPane;
    // End of variables declaration//GEN-END:variables
   
    private final List<JFrame> currentlyOpenWindows = new LinkedList<JFrame>();
    private static final String SEP = File.separator;
    private static final String DEF_OPENNLP_MODEL_PATH  = "models" + SEP + "opennlp";
    private static final String DEF_STANFORD_MODEL_PATH = "models" + SEP + "stanford";
}
